# SVP only to 60 fps. No DLSS 5. This is the original GPU-3-High.

svp=3		# 1 - low | 2 - medium (default) | 3 - high
alg=3		# 1 - simple | 2 - standard (default) | 3 - complex
fim=3		# 1 - average | 2 - adaptive (default) | 3 - uniform
bf=0		# 0 - off (default) | 1 - blending frames
gpu=1		# 0 - off (default) | 1 - first gpu | 2 - second gpu
fps=60		# 60 (default) | 2 - x2 fps | 50 ... 120 - target fps

sh=0		# 0 - off (default) | 1 - avisynth sharpness
uhd=1		# 0 - off (default) | 1 - ultra hd video support
up60=0		# 0 - off (default) | 1 - source support up to 60 fps
demo=0		# 0 - off (default) | 1 - svp demo mode
nr=0		# 0 - off | 1 - DLSS 5 Neural Rendering
smooth=1	# 0 - no interpolation | 1 - SVP to fps=

import("svp.avs")

/*
advanced settings (values)
svp=0 : less smoothness and artifacts (1st fixed preset)
svp=0 + alg=0 : less smoothness and artifacts (2nd fixed preset)
svp=0 + alg=0 + fim=0 : very low cpu usage (3rd fixed preset)
alg=0 : algorithm for 2d animations (slightly less artifacts)
fim=0 : limits scene change detection (slightly less smoothness)
*/
